name = "Create: Back on Track - Lesbian edition"
author = "Octelly"
version = "1.1.4b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b77f48bb38d50bb34fdb3d47de8d95431760754e69301499ca764c36ce6632f"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
