name = "Create: Back on Track - Lesbian edition"
author = "Octelly"
version = "1.1.4b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d72435a93ba7c90b89ac5d45b360dd1aea1275631772aeb91f988028f23d066"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
