name = "Create: Back on Track - Lesbian edition"
author = "Octelly"
version = "1.1.4b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0939751d9c5c4863b5ea44dd9b313cc4e405502ba02509bf9bc5414a06c5887"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
